const state = {
  currentScreen: null,
  accessMode: null,
  authMode: "login",
  customerName: "",
  onlineCustomer: null,
  selectedCategory: "All",
  searchTerm: "",
  selectedItem: null,
  modalQuantity: 1,
  cart: [],
  order: null,
  orderStatusIndex: 0,
  onlineOrders: [],
  accounts: [],
  sessionRequestCode: "",
  sessionApproved: false,
  sessionApprovalTimer: null,
  orderStatusTimers: [],
};
